version: '3.8'

services:
  edgp-ai-model:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - LOG_LEVEL=INFO
      - REDIS_URL=redis://redis:6379/0
      # AWS credentials for external communication
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION:-us-east-1}
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - edgp-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - edgp-network

  # Optional: Monitoring with Prometheus
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - edgp-network
    profiles:
      - monitoring

volumes:
  redis_data:

networks:
  edgp-network:
    driver: bridge
